;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from dm-evil-text.el

(autoload 'dm-evil-text-setup "dm-evil-text"
"Install Daymacs Evil text objects and sort bindings.")
(register-definition-prefixes "dm-evil-text" '("dm-evil-text-"))


;;; Generated autoloads from dm-files.el

(autoload 'dm-directory-open "dm-files"
"Open the directory of the current buffer's file in Finder." t)
(autoload 'dm-directory-open-project "dm-files"
"Open the current project root, falling back to the current directory.
This never prompts for a project." t)
(autoload 'dm-file-open "dm-files"
"Open the current buffer's file with the default or configured app.

Uses `dm-file-open-apps' to choose an app by filename regexp.
Falls back to macOS `open'." t)
(autoload 'dm-copy-file-path "dm-files"
"Copy the current buffer file path with home abbreviated as `~'.

If the file is not under the user's home directory, report nil." t)
(autoload 'dm-copy-file-abspath "dm-files"
"Copy the absolute path of the current buffer's file." t)
(autoload 'dm-copy-file-project-path "dm-files"
"Copy the current buffer file path relative to the project root.

If the file is not inside the current project, report nil." t)
(autoload 'dm-copy-file-path-dwim "dm-files"
"Copy the most useful path for the current buffer file.

Preference order:

1. Project-relative path.
2. Home-abbreviated path.
3. Absolute path.

If the buffer has no file, report that instead." t)
(autoload 'dm-delete-this-file "dm-files"
"Delete the current buffer's file.

(fn &optional PATH)" t)
(autoload 'dm-project-discover-projects "dm-files"
"Discover Git projects under DIRECTORY using fd and remember them with project.el.
DIRECTORY defaults to the user's home directory.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "dm-files" '("dm-"))


;;; Generated autoloads from dm-lisp.el

(register-definition-prefixes "dm-lisp" '("dm-e"))


;;; Generated autoloads from dm-popup-quit.el

(autoload 'dm-quit-or-close-popup "dm-popup-quit"
"Close a visible popup window, or otherwise run `keyboard-quit'.
A popup window is any non-selected visible window whose buffer name is listed
in `dm-quit-or-close-popup-buffer-names' or starts with one of
`dm-quit-or-close-popup-buffer-prefixes'." t)
(register-definition-prefixes "dm-popup-quit" '("dm-quit-or-close-popup-"))


;;; Generated autoloads from dm-test-toggle.el

(autoload 'dm-toggle-test-implementation "dm-test-toggle"
"Toggle between implementation and test file using project.el." t)
(register-definition-prefixes "dm-test-toggle" '("dm-"))


;;; Generated autoloads from dm-text.el

(autoload 'dm-text-latex-wrap-as-math "dm-text"
"Wrap selected text, or text around point, in LaTeX math delimiters.
With DISPLAYMODE-P, use display math delimiters.

(fn DISPLAYMODE-P)" t)
(autoload 'dm-text-latex-wrap-as-math-display "dm-text"
"Wrap selected text, or text around point, in LaTeX display math delimiters." t)
(autoload 'dm-text-latex-wrap-as-frac "dm-text"
"Wrap selected text, or text around point, in a LaTeX fraction command." t)
(autoload 'dm-text-latex-wrap-as-boxed "dm-text"
"Wrap selected text, or text around point, in a LaTeX boxed command." t)
(autoload 'dm-text-latex-wrap-as-si "dm-text"
"Format the selected text as a LaTeX SI unit expression." t)
(autoload 'dm-text-latex-evaluate-selection "dm-text"
"Evaluate selected LaTeX-flavored math and replace it with the result." t)
(autoload 'dm-text-make-bold "dm-text"
"Format selected text, or text around point, as bold." t)
(autoload 'dm-text-make-italic "dm-text"
"Format selected text, or text around point, as italic." t)
(autoload 'dm-text-make-underlined "dm-text"
"Format selected text, or text around point, as underlined." t)
(autoload 'dm-text-make-strikethrough "dm-text"
"Format selected text, or text around point, as strikethrough." t)
(register-definition-prefixes "dm-text" '("dm-text-"))

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
