#!/bin/sh

# git-edit

emacsclient -s tty -t -a '' "$@"
status=$?

[ "$status" -eq 0 ] && exit 0

msgfile="$1"
if ! grep -vE '^[[:space:]]*(#.*)?$' "$msgfile" >/dev/null 2>&1; then
  echo "Aborting commit due to empty commit message."
fi
exit 0
