#!/usr/bin/env bash

# Build p/d binary in local bin directory
# Generate initial project catalog file

set -e

if [[ -z "${SHELL_CONFIG_DIR}" ]]; then
  echo "Error: SHELL_CONFIG_DIR env var not set. Skipping p/d installation."
  exit 1
elif [[ -z "${XDG_LOCALS_DIR}" ]]; then
  echo "Error: XDG_LOCALS_DIR env var not set. Skipping p/d installation."
  exit 1
elif [[ -z "$(command -v mise)" ]]; then
  echo "Error: mise executable not found. Skipping p/d installation."
  exit 1
fi

export MISE_TRUSTED_CONFIG_PATHS="${SHELL_CONFIG_DIR}/share/pd"

builtin cd "${SHELL_CONFIG_DIR}/share/pd"
eval "$(mise activate bash)"
mise use go

if [[ -z "$(command -v go)" ]]; then
  echo "Error: go executable not found. Skipping p/d installation."
  exit 1
fi

go get
go build -o ${XDG_LOCALS_DIR}/bin/pd main.go
pd --pd-refresh &
