[tools]
elixir   = "latest"
erlang   = "latest"
go       = "latest"
hugo     = "0.152.2"
node     = "latest"
perl     = "latest"
postgres = "latest"
python   = "latest"
ruby     = "latest"
rust     = "latest"

"cargo:evcxr_repl"         = "latest"
"github:expert-lsp/expert" = "latest"
"pipx:basedpyright"        = "latest"
"pipx:ruff"                = "latest"

[settings]

[settings.ruby]
compile = false

[tasks.bootstrap]
description = "Install cross-cutting dependencies"
run = """
mise run bootstrap-elixir
mise run bootstrap-go
mise run bootstrap-node
mise run bootstrap-perl
mise run bootstrap-python
mise run bootstrap-ruby
mise run bootstrap-rust
mise reshim
"""

[tasks.bootstrap-elixir]
description = "Install cross-cutting Elixir dependencies"
run = """
mix local.hex --force
mix local.rebar --force
mix archive.install hex phx_new --force
mise reshim elixir
"""

[tasks.bootstrap-go]
description = "Install cross-cutting Go dependencies"
run = """
go install github.com/cweill/gotests/...@latest
go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
go install github.com/fatih/gomodifytags@latest
go install github.com/josharian/impl@latest
go install github.com/x-motemen/gore/cmd/gore@latest
go install golang.org/x/tools/cmd/godoc@latest
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/cmd/gorename@latest
go install golang.org/x/tools/gopls@latest
mise reshim go
"""

[tasks.bootstrap-node]
description = "Install cross-cutting Node dependencies"
run = """
npm install -g \
      @github/copilot-language-server \
      prettier \
      tsx \
      typescript \
      typescript-language-server
"""

[tasks.bootstrap-perl]
description = "Install cross-cutting Perl dependencies"
run = """
cpanm File::HomeDir YAML::Tiny
mise reshim perl
"""

[tasks.bootstrap-python]
description = "Install cross-cutting Python dependencies"
run = """
pip install -U pip
pip install -U \
      ipdb \
      ipython \
      mypy \
      openai \
      pytest \
      pyxdg \
      pyyaml
mise reshim python
"""

[tasks.bootstrap-ruby]
description = "Install cross-cutting Ruby dependencies"
run = """
gem install \
      amazing_print \
      andyw8-seeing_is_believing \
      benchmark-ips \
      colorize \
      debug \
      hirb \
      interactive_editor \
      jazz_fingers \
      rspec \
      rubocop \
      specific_install \
      spicy-proton

ln -sf "${MISE_DIR}/shims/andyw8_seeing_is_believing" \
     "${XDG_SECURE_DIR}/bin/seeing_is_believing"
"""

[tasks.bootstrap-rust]
description = "Install cross-cutting Rust dependencies"
run = """
rustup component add rust-analyzer
mise reshim rust
"""
